### PR TITLE
Use yoshi lint <files> filter on top of files specified in tsconfig [tslint]

### LINKED ISSUE #598: Can't commit fresh app (generated by `create-yoshi-app`)
# 🐛 Bug Report

Can't commit apps that are generated by `create-yoshi-app`, tried templates for `fullstack` (and `universal`), Babel (and Typescript). Also tried run that on Node.js 10.11 - error is the same.

### 😯 Current Behavior

Fresh install of project created by `create-yoshi-app` can't be committed (pre-commit hooks failed).
```sh
$ git add .
$ git commit -m "initial commit"

Found '/Users/serhiis/projects/example-app/.nvmrc' with version <8.9.1>
Now using node v8.9.1 (npm v5.5.1)
Found '/Users/serhiis/projects/example-app/.nvmrc' with version <8.9.1>
Now using node v8.9.1 (npm v5.5.1)
husky > npm run -s precommit (node v8.9.1)

 ❯ Running tasks for *.{js,ts,tsx,scss,less}
   ✖ yoshi lint
✖ "yoshi lint" found some errors. Please fix them and try committing again.
running tslint on /Users/serhiis/projects/example-app/test/server/server.spec.ts,/Users/serhiis/projects/example-app/test/helpers/i18n.mock.ts,/Users/serhiis/projects/example-app/test/environment.ts,/Users/serhiis/projects/example-app/test/e2e/app.spec.ts,/Users/serhiis/projects/example-app/src/test-types.d.ts,/Users/serhiis/projects/example-app/src/server.ts,/Users/serhiis/projects/example-app/src/i18n.ts,/Users/serhiis/projects/example-app/src/external-types.d.ts,/Users/serhiis/projects/example-app/src/components/App/index.ts,/Users/serhiis/projects/example-app/src/components/App/App.tsx,/Users/serhiis/projects/example-app/src/components/App/App.spec.tsx,/Users/serhiis/projects/example-app/src/client.tsx
/Users/serhiis/projects/example-app/src/test-types.d.ts:7:9
ERROR: 7:9  prettier  Delete `·`

/Users/serhiis/projects/example-app/src/components/App/App.spec.tsx:2:9
ERROR: 2:9    prettier  Replace `mount` with `·mount·`
ERROR: 3:9    prettier  Replace `I18nextProvider` with `·I18nextProvider·`
ERROR: 15:13  prettier  Insert `·`


Warning: The 'await-promise' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-for-in-array' rule requires type information.
Warning: The 'restrict-plus-operands' rule requires type information.
Warning: The 'use-default-type-parameter' rule requires type information.
Warning: The 'deprecation' rule requires type information.
Warning: The 'prefer-readonly' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
tslint exited with 4 errors (4 fixable)

husky > pre-commit hook failed (add --no-verify to bypass)
```

### 🤔 Expected Behavior

Fresh install of generated app is able to be committed.

### 💻 Code Sample

Can't provide repository, cause fresh app can't be committed.

### 🌍 Your Environment

```sh
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.2
    Safari: 12.0
  npmPackages:
    yoshi: ^3.0.0 => 3.11.0

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

### PR DESCRIPTION
**Pull request by ranyitz**
### 🔦 Summary
This PR fixes #598 By applying the files supplied to TSLint as a filter above the files that specified using `include/exclude/files` in `tsconfig.json`.

It should create a more coherent lint process, making sure `yoshi lint` catches all the error and lint using the [type checker](https://palantir.github.io/tslint/usage/type-checking/)

It will still show a warning for files will not be linted but specified in after the `yoshi lint` command.

image

### 🗺️ Test Plan
* Change current tests to ignore files that were not specified in the `tsconfig.json`.
* Add a test for the provided warning.

### CODE REVIEW

File: packages/yoshi/src/tasks/tslint.js [hunk 1]
```diff
@@ -21,32 +22,38 @@ function format(options, fileFailures) {
...
-    files = Linter.getFileNames(program).map(fileName => ({
-      fileName,
-      fileContents: program.getSourceFile(fileName).getFullText(),
-    }));
+  let filePaths = linterFileNames;
+
+  if (filterPaths) {
+    filePaths = intersection(filterPaths, linterFileNames);
+
+    if (!isEqual(filePaths, filterPaths)) {
```
Comment (netanelgilad) [inline packages/yoshi/src/tasks/tslint.js]: A very small point, but you can just calculate the `difference` instead of doing `isEqual` and then `difference`. You can just check that `calculatedDiff.length > 0`.
