### PR TITLE
fix wallaby configuration when working with jest

### LINKED ISSUE #611: Wallaby fails for fresh app (generated by `create-yoshi-app`)
# 🐛 Bug Report

### 😯 Current Behavior

I created an app with `create-yoshi-app` with `fullstack` and `TypeScript` (as part of my onboarding [Zero to Production](https://github.com/wix-private/fed-handbook/blob/master/ZERO_TO_PRODUCTION.md)) and when I started wallaby (in WebStorm), I got these errors:
```
4 failing tests, 0 passing 

test/server/server.spec.ts When rendering should display a title [3 ms]

	app is not defined
		at Object.<anonymous> test/server/server.spec.ts:5
		at Context.<anonymous> test/server/server.spec.ts:4

test/e2e/app.spec.ts React application should display google image [0 ms]

	page is not defined
		at Object.<anonymous> test/e2e/app.spec.ts:10
		at Context.<anonymous> test/e2e/app.spec.ts:9

test/e2e/app.spec.ts React application should display title [3 ms]

	page is not defined
		at Object.<anonymous> test/e2e/app.spec.ts:3
		at Context.<anonymous> test/e2e/app.spec.ts:2

src/components/App/App.spec.tsx App renders a title correctly [2 ms]

	It looks like you called `mount()` without a global document being loaded.
		at Context.<anonymous> src/components/App/App.spec.tsx:13


```

### 🤔 Expected Behavior

Wallaby should run green with no errors.

### 🌍 Your Environment
```
> npx yoshi info
 System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    yoshi: ^3.0.0 => 3.14.1

 Yoshi config
{
  "externals": {
    "react": "React",
    "react-dom": "ReactDOM"
  },
  "hmr": "auto"
}
```

### PR DESCRIPTION
**Pull request by netanelgilad**
### 🔦 Summary
Fixes #611. Wallaby will now work with jest, but only with unit/component tests. As wallaby is not intended for e2e/server tests, it didn't make sense to try to make it work with those projects. ([More from wallaby maintainers](https://github.com/wallabyjs/public/issues/1144#issuecomment-299350559)).

### 🗺️ Test Plan
If only we could test wallaby....

### CODE REVIEW

File: packages/yoshi/config/wallaby-mocha.js [hunk 1]
```diff
@@ -1,5 +1,21 @@
 module.exports = function(wallaby) {
   const wallabyCommon = require('./wallaby-common')(wallaby);
+  wallabyCommon.tests = [
+    ...[
```
Comment (splintor) [inline packages/yoshi/config/wallaby-mocha.js]: instead of building an array and then extracting it with `...` why not simply list the items:
wallabyCommon.tests = [
  { pattern: 'test/**/*.+(spec|it).[j|t]s' },
  { pattern: 'test/**/*.+(spec|it).[j|t]sx' },
  ...wallabyCommon.tests
];

Comment (netanelgilad) [reply packages/yoshi/config/wallaby-mocha.js]: You are absolutely right, guess I was blind to the obvious :). A PR would be welcome 🍻
